spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/hibernate_batch?profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=200&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        check_nullability: true
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 2000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

logging:
  level:
    org.hibernate:
      SQL: debug